### ISSUE TITLE
Замечания по паттерну "Наблюдатель"

### ISSUE THREAD

**Issue by alexey-malov** [matjukov-nikolaj/OOD#2]
- [ ] Заменить Integer на int в методе registerObserver

**Comment by alexey-malov** [comment]
- [ ] Избавиться от избыточной сортировки элементов в notifyObservers

**Comment by alexey-malov** [comment]
- [ ] Метод removeObserver использует какую-то мудрёную логику вместо обычного сравнения объектов.

**Comment by iandreyshev** [comment]
- [ ] Избавиться от наследования от BasicDisplayImpl, заменить на композицию в классах дисплеев
- [ ] Для проверки удаления обсерверов и правильного уведомления обсерверов с приоритетом написать разные тесты
